### ISSUE TITLE
Failed to create cache dir >   at io.vertx.core.file.impl.FileResolver.setupCacheDir(FileResolver.java:332) on Nimble CSP pod

### ISSUE THREAD

**Issue by rafapiltrafa** [hpe-storage/csi-driver#402]
Hi!! 

we have just upgraded from HPE CSI Driver 2.4.0 to 2.4.2 on OCP 4.14.20(with the recommended upgrade plan: delete HPE CSI Driver instance, delete CRD, uninstall 2.4.0 operator , install 2.4.2 operator and create HPE CSI Driver instance). We don't use Nimble in our deployment but the Nimble CSP keeps crashing with this error:

Exception in thread "main" java.lang.RuntimeException: Failed to start quarkus
        at io.quarkus.runner.ApplicationImpl.doStart(ApplicationImpl.zig:275)
        at io.quarkus.runtime.Application.start(Application.java:87)
        at io.quarkus.runtime.Application.run(Application.java:210)
        at io.quarkus.runner.GeneratedMain.main(GeneratedMain.zig:41)
Caused by: java.lang.IllegalStateException: Failed to create cache dir
        at io.vertx.core.file.impl.FileResolver.setupCacheDir(FileResolver.java:332)
        at io.vertx.core.file.impl.FileResolver.<init>(FileResolver.java:87)
        at io.vertx.core.impl.VertxImpl.<init>(VertxImpl.java:167)
        at io.vertx.core.impl.VertxImpl.vertx(VertxImpl.java:92)
        at io.vertx.core.impl.VertxFactoryImpl.vertx(VertxFactoryImpl.java:40)
        at io.vertx.core.impl.VertxFactoryImpl.vertx(VertxFactoryImpl.java:32)
        at io.vertx.core.Vertx.vertx(Vertx.java:85)
        at io.quarkus.vertx.core.runtime.VertxCoreRecorder.initializeWeb(VertxCoreRecorder.java:105)
        at io.quarkus.vertx.core.runtime.VertxCoreRecorder.initializeWeb(VertxCoreRecorder.java:87)
        at io.quarkus.deployment.steps.VertxCoreProcessor$buildWeb34.deploy_0(VertxCoreProcessor$buildWeb34.zig:69)
        at io.quarkus.deployment.steps.VertxCoreProcessor$buildWeb34.deploy(VertxCoreProcessor$buildWeb34.zig:94)
        at io.quarkus.runner.ApplicationImpl.doStart(ApplicationImpl.zig:173)
        ... 3 more

with HPE CSI Driver 2.4.0 all worked right.

It seemns a problem with  "io.vertx.core.file.impl.FileResolver.setupCacheDir" (vertx.disableFileCPResolving -> true or setup a dir in which can be created the cache dir) 

 oc get pods -n hpe-storage
NAME                                                   READY   STATUS             RESTARTS        AGE
hpe-csi-controller-769f5648fb-fqsh8                    9/9     Running            0               87m
hpe-csi-node-5nngh                                     2/2     Running            0               87m
hpe-csi-node-77dvl                                     2/2     Running            0               87m
hpe-csi-node-9l8tr                                     2/2     Running            0               87m
hpe-csi-operator-controller-manager-56d66b96c9-5glbw   2/2     Running            0               108m
nimble-csp-b5f68df74-8jxnq                             0/1     CrashLoopBackOff   6 (2m32s ago)   8m22s <<<<<<<<<<<
primera3par-csp-55d5db7dcf-lm7br                       1/1     Running            0               87m

  nimble-csp:
    Container ID:   cri-o://99bf803d92fea81d9090f24d71d8e894635d9844131ffca0c5c202f0956fc1c4
    Image:          quay.io/hpestorage/alletra-6000-and-nimble-csp:v2.4.1
    Image ID:       quay.io/hpestorage/alletra-6000-and-nimble-csp@sha256:19044496a912433dd1bc17cfdbc0cef8bfe8f24261e3a59c0fb9d3a1ab4f2a83

Thanks !
Regards

**Comment by rafapiltrafa** [comment]
Hi Michael !

Thanks a lot for your help.

It has work perfectly:

NAME                                                   READY   STATUS    RESTARTS   AGE
hpe-csi-controller-769f5648fb-fqsh8                    9/9     Running   0          7h45m
hpe-csi-node-5nngh                                     2/2     Running   0          7h45m
hpe-csi-node-77dvl                                     2/2     Running   0          7h45m
hpe-csi-node-9l8tr                                     2/2     Running   0          7h45m
hpe-csi-operator-controller-manager-56d66b96c9-5glbw   2/2     Running   0          8h
nimble-csp-b5f68df74-cwvfv                             1/1     Running   0          2s  <<<<<<<<<<<<<
primera3par-csp-55d5db7dcf-lm7br                       1/1     Running   0          7h45m


thanks !
Regards
Rafa

**Comment by rafapiltrafa** [comment]
It would be great if the doc is modified with this info for future reference, 

thanks !!

**Comment by datamattsson** [comment]
Thanks for the feedback and I'll add a note to the docs with this
prerequisite. I'm glad it worked for you.
