### ISSUE TITLE
Unexpected argument 'multi_initiator'

### ISSUE THREAD

**Issue by raffis** [hpe-storage/csi-driver#45]
I'm trying to get the csi  hpe provisioning working but end up with the error `Unexpected argument 'multi_initiator'`.

Nimble:  5.0.7.300-644174-opt 

csi-provisioner:
```
I0927 09:34:47.698020       1 controller.go:481] CreateVolumeRequest {Name:pvc-40a9a047-13e3-487f-981b-7af701f11cf1 CapacityRange:required_bytes:10737418240  VolumeCapabilities:[mount:<fs_type:"xfs" > access_mode:<mode:SINGLE_NODE_WRITER > ] Parameters:map[accessProtocol:fc csi.storage.k8s.io/controller-publish-secret-name:nimble-secret csi.storage.k8s.io/controller-publish-secret-namespace:kube-system csi.storage.k8s.io/fstype:xfs csi.storage.k8s.io/node-publish-secret-name:nimble-secret csi.storage.k8s.io/node-publish-secret-namespace:kube-system csi.storage.k8s.io/node-stage-secret-name:nimble-secret csi.storage.k8s.io/node-stage-secret-namespace:kube-system csi.storage.k8s.io/provisioner-secret-name:nimble-secret csi.storage.k8s.io/provisioner-secret-namespace:kube-system description:Volume provisioned by the HPE CSI Driver limitIops:76800] Secrets:map[] VolumeContentSource:<nil> AccessibilityRequirements:<nil> XXX_NoUnkeyedLiteral:{} XXX_unrecognized:[] XXX_sizecache:0}
I0927 09:34:47.698214       1 event.go:255] Event(v1.ObjectReference{Kind:"PersistentVolumeClaim", Namespace:"default", Name:"testpvc1", UID:"40a9a047-13e3-487f-981b-7af701f11cf1", APIVersion:"v1", ResourceVersion:"26527162", FieldPath:""}): type: 'Normal' reason: 'Provisioning' External provisioner is provisioning volume for claim "default/testpvc1"
I0927 09:34:47.704997       1 connection.go:180] GRPC call: /csi.v1.Controller/CreateVolume
I0927 09:34:47.705033       1 connection.go:181] GRPC request: {"capacity_range":{"required_bytes":10737418240},"name":"pvc-40a9a047-13e3-487f-981b-7af701f11cf1","parameters":{"accessProtocol":"fc","description":"Volume provisioned by the HPE CSI Driver","limitIops":"76800"},"secrets":"***stripped***","volume_capabilities":[{"AccessType":{"Mount":{"fs_type":"xfs"}},"access_mode":{"mode":1}}]}
I0927 09:34:49.175415       1 connection.go:183] GRPC response: {}
I0927 09:34:49.176087       1 connection.go:184] GRPC error: rpc error: code = Internal desc = Failed to create volume pvc-40a9a047-13e3-487f-981b-7af701f11cf1 due to error: status code was 400 Bad Request for request: action=POST path=http://nimble-csp-svc:8080/containers/v1/volumes
I0927 09:34:49.176167       1 controller.go:979] Final error received, removing PVC 40a9a047-13e3-487f-981b-7af701f11cf1 from claims in progress
W0927 09:34:49.176186       1 controller.go:886] Retrying syncing claim "40a9a047-13e3-487f-981b-7af701f11cf1", failure 8
```

csp-service:
```
09:31:33 DEBUG [co.ni.hi.ut.ExecutionManager]] (executor-thread-1) executeTask-1569576693091: Waiting for result from command CreateVolume.
09:31:33 DEBUG [co.ni.hi.ut.ExecutionManager]] (executor-thread-1) executeTask-1569576693091: Processing result from command CreateVolume.
09:31:33 DEBUG [co.ni.hi.ut.ExecutionManager]] (executor-thread-1) executeTask-1569576693091: Added result from command CreateVolume to chain.results. Id: CreateVolume, Result: null.
09:31:33 ERROR [co.ni.hi.ut.ExecutionManager]] (executor-thread-1) executeTask-1569576693091: Command [id=CreateVolume, name=CreateVolume] has reported an exception.
09:31:33 DEBUG [co.ni.hi.ut.ExecutionManager]] (executor-thread-1) rollBack-1569576693091: called on 70317b2c-dd1b-42f5-94ac-bc7bf596c8c5
09:31:33 DEBUG [co.ni.hi.ut.ExecutionManager]] (executor-thread-1) rollBack-1569576693091: Looking for any commands that needed to stop executing.
09:31:34 ERROR [co.ni.hi.cs.se.er.GroupMgmtServerExceptionMapper]] (executor-thread-1) Bad request: com.nimblestorage.nos.groupmgmt.GroupMgmtServerException: HTTP 400 OK ([{ code: SM_http_bad_request,
 text: The request could not be understood by the server.,
 arguments: null}
, { code: SM_unexpected_arg,
 text: Unexpected argument 'multi_initiator'.,
 arguments: {arg=multi_initiator}}
])
	at com.nimblestorage.nos.groupmgmt.GroupMgmtClient.invoke(GroupMgmtClient.java:776)
	at com.nimblestorage.nos.groupmgmt.GroupMgmtClient.invoke(GroupMgmtClient.java:737)
	at com.nimblestorage.nos.groupmgmt.GroupMgmtClient.post(GroupMgmtClient.java:733)
	at com.nimblestorage.nos.groupmgmt.v1.objectset.VolumeObjectSet.createObject(VolumeObjectSet.java:261)
	at com.nimblestorage.hi.nos.group.VolumeService.createVolume(VolumeService.java:606)
	at com.nimblestorage.hi.nos.group.VolumeService.createVolume(VolumeService.java:596)
	at com.nimblestorage.hi.csp.v1.commands.CreateVolume.execute(CreateVolume.java:144)
	at com.nimblestorage.hi.utils.Command.call(Command.java:40)
	at com.nimblestorage.hi.utils.Command.call(Command.java:21)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
	at com.oracle.svm.core.thread.JavaThreads.threadStartRoutine(JavaThreads.java:460)
	at com.oracle.svm.core.posix.thread.PosixJavaThreads.pthreadStartRoutine(PosixJavaThreads.java:193)
Caused by: javax.ws.rs.BadRequestException: HTTP 400 OK
	at org.glassfish.jersey.client.JerseyInvocation.convertToException(JerseyInvocation.java:1053)
	at org.glassfish.jersey.client.JerseyInvocation.translate(JerseyInvocation.java:924)
	at org.glassfish.jersey.client.JerseyInvocation.lambda$invoke$2(JerseyInvocation.java:763)
	at org.glassfish.jersey.internal.Errors.process(Errors.java:292)
	at org.glassfish.jersey.internal.Errors.process(Errors.java:274)
	at org.glassfish.jersey.internal.Errors.process(Errors.java:205)
	at org.glassfish.jersey.process.internal.RequestScope.runInScope(RequestScope.java:390)
	at org.glassfish.jersey.client.JerseyInvocation.invoke(JerseyInvocation.java:761)
	at com.nimblestorage.nos.groupmgmt.GroupMgmtClient.invoke(GroupMgmtClient.java:744)
	... 16 more

```

storage class:
```
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"storage.k8s.io/v1","kind":"StorageClass","metadata":{"annotations":{},"creationTimestamp":"2019-09-18T10:26:12Z","name":"generic-nimble-csi","resourceVersion":"24853915","selfLink":"/apis/storage.k8s.io/v1/storageclasses/generic-nimble-csi","uid":"edddbb4f-f1ca-4b18-ad4b-cdaa6f1fa52d"},"parameters":{"accessProtocol":"fc","csi.storage.k8s.io/controller-publish-secret-name":"nimble-secret","csi.storage.k8s.io/controller-publish-secret-namespace":"kube-system","csi.storage.k8s.io/fstype":"xfs","csi.storage.k8s.io/node-publish-secret-name":"nimble-secret","csi.storage.k8s.io/node-publish-secret-namespace":"kube-system","csi.storage.k8s.io/node-stage-secret-name":"nimble-secret","csi.storage.k8s.io/node-stage-secret-namespace":"kube-system","csi.storage.k8s.io/provisioner-secret-name":"nimble-secret","csi.storage.k8s.io/provisioner-secret-namespace":"kube-system","description":"Volume provisioned by the HPE CSI Driver","limitIops":"76800"},"provisioner":"csi.hpe.com","reclaimPolicy":"Delete","volumeBindingMode":"Immediate"}
  creationTimestamp: "2019-09-27T09:29:50Z"
  name: generic-nimble-csi
  resourceVersion: "26527081"
  selfLink: /apis/storage.k8s.io/v1/storageclasses/generic-nimble-csi
  uid: 3c846177-6b9d-4642-8cb8-d22dd89c861c
parameters:
  accessProtocol: fc
  csi.storage.k8s.io/controller-publish-secret-name: nimble-secret
  csi.storage.k8s.io/controller-publish-secret-namespace: kube-system
  csi.storage.k8s.io/fstype: xfs
  csi.storage.k8s.io/node-publish-secret-name: nimble-secret
  csi.storage.k8s.io/node-publish-secret-namespace: kube-system
  csi.storage.k8s.io/node-stage-secret-name: nimble-secret
  csi.storage.k8s.io/node-stage-secret-namespace: kube-system
  csi.storage.k8s.io/provisioner-secret-name: nimble-secret
  csi.storage.k8s.io/provisioner-secret-namespace: kube-system
  description: Volume provisioned by the HPE CSI Driver
  limitIops: "76800"
provisioner: csi.hpe.com
reclaimPolicy: Delete
volumeBindingMode: Immediate
```

**Comment by raffis** [comment]
It does work with csp v1.0.0-beta (https://github.com/hpe-storage/co-deployments/pull/51).
Is multi_initiator an argument for some alpha version of the nimble api?
Anyway the kube specs in master should point to stable or at least beta tags.

**Comment by rgcostea** [comment]
@raffis - This is a bug on our end.  We have done minimal testing with FC arrays.  We will fix it within the CSP implementation.  Thanks for pointing this out.
